# Generated by Django 3.1.7 on 2021-03-26 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag_color'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipes.Recipe', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='shopping_list', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='_user_subscribes_+', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
