# Generated by Django 3.1.7 on 2021-04-05 12:48

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210405_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=28, unique=True, validators=[users.validators.validate_name], verbose_name='name'),
        ),
    ]
