version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  app:
    build: .
    restart: always
    container_name: app
    volumes:
      - ./static/:/app/static/
      - ./media/:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env 
  web:
    image: nginx:1.19
    container_name: web
    volumes:
      - ./helpers/templates:/etc/nginx/templates
      - ./static/:/app/static/
      - ./media/:/app/media/
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=yatubetest.ml
      - NGINX_PORT=80
    depends_on:
      - app
