# Generated by Django 3.1.7 on 2021-03-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210323_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='green', max_length=30),
        ),
    ]
