# Generated by Django 3.1.7 on 2021-04-01 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(600), django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления в минутах'),
        ),
    ]
