# Generated by Django 3.1.7 on 2021-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210405_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='green', max_length=30, verbose_name='Цвет (дополняет класс элемента dom)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Название тэга'),
        ),
    ]
